name: Custom Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:
    name: Build site with Jekyll
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare static files
        run: |
          mkdir -p _site
          cp -R src/* _site/
        # Adjust "src" to your actual source directory

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./_site

  deploy:
    runs-on: [self-hosted, macOS, ARM64]
    needs: build

    steps:
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages