name: Custom Deploy

on:
    push:
        branches:
            - gh-pages
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build site with Jekyll
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare static files
        run: |
          mkdir -p _site
          cp -R ./* _site/
        # Adjust "src" to your actual source directory

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./_site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    # <- Not self-hosted!
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4