name: Custom Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build site with Jekyll
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare static files
        run: |
          mkdir -p _site
          cp -R ./* _site/
        # Adjust "src" to your actual source directory

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./_site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: github-pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./_site

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site